module.exports = {
  "colors": {
    "50": "var(--color-50)",
    "100": "var(--color-100)",
    "200": "var(--color-200)",
    "300": "var(--color-300)",
    "400": "var(--color-400)",
    "500": "var(--color-500)",
    "600": "var(--color-600)",
    "700": "var(--color-700)",
    "800": "var(--color-800)",
    "900": "var(--color-900)",
    "Success": "var(--color-Success)",
    "Info": "var(--color-Info)",
    "Warning": "var(--color-Warning)",
    "Error": "var(--color-Error)",
    "Light Disabled": "var(--color-Light Disabled)",
    "Dark Disabled": "var(--color-Dark Disabled)",
    "Button Disabled": "var(--color-Button Disabled)",
    "Gradient Red": "var(--color-Gradient Red)",
    "Gradient Teal": "var(--color-Gradient Teal)",
    "Gradient Purple": "var(--color-Gradient Purple)",
    "Gradient Blue": "var(--color-Gradient Blue)",
    "Gradient Green": "var(--color-Gradient Green)",
    "Gradient Brown": "var(--color-Gradient Brown)",
    "Gradient Yellow": "var(--color-Gradient Yellow)",
    "Gradident Orange": "var(--color-Gradident Orange)",
    "White": "var(--color-White)",
    "Black": "var(--color-Black)",
    "Red": "var(--color-Red)",
    "Pink": "var(--color-Pink)",
    "Purple": "var(--color-Purple)",
    "Deep Purple": "var(--color-Deep Purple)",
    "Indigo": "var(--color-Indigo)",
    "Blue": "var(--color-Blue)",
    "Light Blue": "var(--color-Light Blue)",
    "Cyan": "var(--color-Cyan)",
    "Teal": "var(--color-Teal)",
    "Green": "var(--color-Green)",
    "Light Green": "var(--color-Light Green)",
    "Lime": "var(--color-Lime)",
    "Yellow": "var(--color-Yellow)",
    "Amber": "var(--color-Amber)",
    "Orange": "var(--color-Orange)",
    "Deep Orange": "var(--color-Deep Orange)",
    "Brown": "var(--color-Brown)",
    "Blue Grey": "var(--color-Blue Grey)",
    "Dark 1": "var(--color-Dark 1)",
    "Dark 2": "var(--color-Dark 2)",
    "Dark 3": "var(--color-Dark 3)",
    "Dark 4": "var(--color-Dark 4)",
    "Dark 5": "var(--color-Dark 5)"
  },
  "spacing": {},
  "borderRadius": {}
};